### PR TITLE
update command from `list -g` to `graph`

### PR DESCRIPTION
**Pull request by dirk-thomas**
Follow up of colcon/colcon-package-information#23.

### CODE REVIEW

**Review by thomas-moulard — APPROVED** [review]
Thanks for updating the README!

**Comment by dirk-thomas** [comment]
@thomas-moulard Friendly ping to get this reviewed and merged.

**Review by jacobperron — APPROVED** [review]

**Comment by dirk-thomas** [comment]
@thomas-moulard Please look into the failing CI.

**Comment by thomas-moulard** [comment]
We're looking into it.

**Comment by piraka9011** [comment]
@thomas-moulard @dirk-thomas see #20 for the fix.

**Comment by thomas-moulard** [comment]
Merged master into this PR branch - this should fix the pipeline build and allow us to merge this in.

**Pull request merged**
